# -*- coding: utf-8 -*-
"""CO1AT1Q02.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1luNVdJDs50lpt26fMEmTv4ip408FXsvN
"""

import cv2
import matplotlib.pyplot as plt

# Read the original image
img = cv2.imread("sample.jpg")

# Convert from BGR to RGB
img = cv2.cvtColor(img, cv2.COLOR_BGR2RGB)

# -------------------------------
# Simulate Low-Light Image
# -------------------------------
# Reduce brightness
low_light = cv2.convertScaleAbs(img, alpha=0.4, beta=0)

# -------------------------------
# Enhance the Image
# -------------------------------
# Increase brightness and contrast
enhanced = cv2.convertScaleAbs(low_light, alpha=1.8, beta=30)

# -------------------------------
# Display Images
# -------------------------------
plt.figure(figsize=(15,5))

plt.subplot(1,3,1)
plt.imshow(img)
plt.title("Original Image")
plt.axis("off")

plt.subplot(1,3,2)
plt.imshow(low_light)
plt.title("Low-Light Image")
plt.axis("off")

plt.subplot(1,3,3)
plt.imshow(enhanced)
plt.title("Enhanced Image")
plt.axis("off")

plt.show()
