# -*- coding: utf-8 -*-
"""CO1AT1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1mVrZDxklg9DBMCr_5JEJAOwbQByRcybk
"""

import cv2
import matplotlib.pyplot as plt

# Read original image
img = cv2.imread("sample.jpg")

# Convert BGR to RGB
img = cv2.cvtColor(img, cv2.COLOR_BGR2RGB)

# Simulate improper sampling (downsample)
low_sample = cv2.resize(img, (100, 100), interpolation=cv2.INTER_AREA)

# Correct using Bicubic Interpolation (upsample)
corrected = cv2.resize(low_sample, (img.shape[1], img.shape[0]),
                       interpolation=cv2.INTER_CUBIC)

# Display images
plt.figure(figsize=(12,5))

plt.subplot(1,3,1)
plt.imshow(img)
plt.title("Original Image")
plt.axis("off")

plt.subplot(1,3,2)
plt.imshow(low_sample)
plt.title("Low Sampled Image")
plt.axis("off")

plt.subplot(1,3,3)
plt.imshow(corrected)
plt.title("Corrected (Bicubic)")
plt.axis("off")

plt.show()
