# -*- coding: utf-8 -*-
"""CO1AT01Q08.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1LlSL8SpI1Ww5in5AaUAzXxEaetsACwoV
"""

import cv2
import numpy as np
import matplotlib.pyplot as plt

img = cv2.imread("sample.jpg")

noise = np.random.normal(0,25,img.shape).astype(np.uint8)
noisy = cv2.add(img, noise)

denoise = cv2.GaussianBlur(noisy,(5,5),0)

plt.figure(figsize=(12,4))

plt.subplot(131)
plt.imshow(cv2.cvtColor(img,cv2.COLOR_BGR2RGB))
plt.title("Original")

plt.subplot(132)
plt.imshow(cv2.cvtColor(noisy,cv2.COLOR_BGR2RGB))
plt.title("Noisy")

plt.subplot(133)
plt.imshow(cv2.cvtColor(denoise,cv2.COLOR_BGR2RGB))
plt.title("Denoised")

plt.show()
