# -*- coding: utf-8 -*-
"""C01AT01Q04.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1zfjFdi8y08zV-2tZW7SUge7PcpESRDRW
"""

import cv2
import matplotlib.pyplot as plt

img = cv2.imread("sample.jpg", 0)

# Low Pixel Resolution
low_res = cv2.resize(img, (100,100))
low_res = cv2.resize(low_res, (img.shape[1], img.shape[0]))

# Low Intensity Resolution (16 levels)
intensity = (img // 16) * 16

plt.figure(figsize=(12,4))

plt.subplot(131)
plt.imshow(img, cmap='gray')
plt.title("Original")
plt.axis("off")

plt.subplot(132)
plt.imshow(low_res, cmap='gray')
plt.title("Low Pixel Resolution")
plt.axis("off")

plt.subplot(133)
plt.imshow(intensity, cmap='gray')
plt.title("Low Intensity Resolution")
plt.axis("off")

plt.show()
