# -*- coding: utf-8 -*-
"""CO1AT01Q07.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/11c7L_L94hJJ5p0uXrBJVLB89yM7vlli_
"""

import cv2
import matplotlib.pyplot as plt

img = cv2.imread("sample.jpg",0)

quantized = (img//32)*32

plt.figure(figsize=(8,4))

plt.subplot(121)
plt.imshow(img,cmap='gray')
plt.title("Original")

plt.subplot(122)
plt.imshow(quantized,cmap='gray')
plt.title("Quantized Image")

plt.show()
