# -*- coding: utf-8 -*-
"""CO1AT01Q05.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1wV9_MoTXHp6h4iVn7o32hxIKzC96oWPQ
"""

import cv2

cap = cv2.VideoCapture(0)

if not cap.isOpened():
    print("Error: Could not open video stream or file.")
    exit()

while True:
    ret, frame = cap.read()

    if not ret:
        print("Error: Failed to receive frame from camera. Exiting...")
        break

    gray = cv2.cvtColor(frame, cv2.COLOR_BGR2GRAY)

    cv2.imshow("Real-Time Surveillance", gray)

    if cv2.waitKey(1) & 0xFF == ord('q'):
        break

cap.release()
cv2.destroyAllWindows()
