# -*- coding: utf-8 -*-
"""CO1AT1Q03.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1wyzIfngypOuQlnVXtepw1jpz1uXc63-u
"""

import cv2
import matplotlib.pyplot as plt

# Read image
img = cv2.imread("sample.jpg")
img = cv2.cvtColor(img, cv2.COLOR_BGR2RGB)

# -----------------------------
# Simulate aliasing
# -----------------------------
# Downsample the image
small = cv2.resize(img, (100, 100), interpolation=cv2.INTER_NEAREST)

# Upsample using nearest neighbour (creates aliasing)
aliased = cv2.resize(small, (img.shape[1], img.shape[0]),
                     interpolation=cv2.INTER_NEAREST)

# -----------------------------
# Correct aliasing
# -----------------------------
# Smooth image before resizing
blur = cv2.GaussianBlur(img, (5,5), 0)

# Downsample and upsample using bicubic interpolation
small2 = cv2.resize(blur, (100,100), interpolation=cv2.INTER_AREA)
corrected = cv2.resize(small2, (img.shape[1], img.shape[0]),
                       interpolation=cv2.INTER_CUBIC)

# -----------------------------
# Display Results
# -----------------------------
plt.figure(figsize=(15,5))

plt.subplot(1,3,1)
plt.imshow(img)
plt.title("Original Image")
plt.axis("off")

plt.subplot(1,3,2)
plt.imshow(aliased)
plt.title("Aliased Image")
plt.axis("off")

plt.subplot(1,3,3)
plt.imshow(corrected)
plt.title("Corrected Image")
plt.axis("off")

plt.show()
