# -*- coding: utf-8 -*-
"""C01AT01Q06.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1lXhrhSe8s8NjiN-6z7sWnpc80fdKt7Fh
"""

import cv2
import matplotlib.pyplot as plt

img = cv2.imread("sample.jpg")

blur = cv2.GaussianBlur(img, (7,7), 0)
sharp = cv2.addWeighted(img, 1.5, blur, -0.5, 0)

plt.figure(figsize=(10,4))

plt.subplot(121)
plt.imshow(cv2.cvtColor(img, cv2.COLOR_BGR2RGB))
plt.title("Original")

plt.subplot(122)
plt.imshow(cv2.cvtColor(sharp, cv2.COLOR_BGR2RGB))
plt.title("Enhanced")

plt.show()
